Dev/oo 723 making zusatzabo accessible in lieferplanung
OpenOlitor/openolitor-server pull request #314
Opened 2017-09-20 12:49 UTC by mcmpp

2017-09-20 12:52 UTC, AlwinEgger approved these changes

2017-09-20 20:40 UTC, toggm requested changes

2017-09-20 20:40 UTC, toggm commented on src/main/scala/ch/openolitor/stammdaten/repositories/StammdatenRepositoryQueries.scala
> +          //val abotyp = abotypen find (_.id == l.abotypId) match {
Remove commented code

2017-09-21 11:37 UTC, mcmpp commented on src/main/scala/ch/openolitor/stammdaten/repositories/StammdatenRepositoryQueries.scala
> +          //val abotyp = abotypen find (_.id == l.abotypId) match {
done

2017-09-21 12:16 UTC, merged