Dev/second factor with otp
OpenOlitor/openolitor-server pull request #580
Opened 2021-01-28 20:37 UTC by toggm

2021-04-09 13:03 UTC, AlwinEgger requested changes
Merci @toggm für den PR! Hier mein Testresultat (für alle PR auch auf den UI Projekten):

Ich habe lokal den aktuellen Datenstand eines Projekts als Grundlage genommen; alle 3 PRs der Projekte ausgecheckt):

- In Core habe ich kleine Änderungen gemacht (einige Buttons kleiner).

**Testfälle:**

1. Wenn ich als User in meinen Einstellungen den 2nd-Factor-Typ auf OTP wechsle und speichere, werde ich nicht zum initialen Secret-Setzen geführt. Beim ersten Login kommt dies dann. Das ist etwas verwirrlich. Sonst klappts dann gut.
2. Als Admin OTP für User zurücksetzen funktioniert. Möglichkeit zur Verbesserung: **Auch für eigenen User(!) und damit brechen wir die im Punkt 4. umgesetzte Sicherheit.** 
3. OTP wieder verlassen über User-Einstellungen funktioniert auch.
4. Second-Factor per E-Mail geht weiterhin. Besoners schön: Für Wechsel zwischen 2nd-Factor Typen muss erst mit 2nd Factor bestätigt werden.
5. Als Kunde mit aktiviertem OTP werde ich auf dem Kundenportal nach dem User/Passwort Login zum aufsetzen des OTP aufgefordert. Nach QR-Code-Scan und Eingabe des Codes werde ich zurück auf die Login-Maske geleitet. **Dann Loop. Erfolgreich einloggen nicht möglich.** Wenn ich mit diesem User auf Admin-Portal einlogge, kann ich die OTP-Aktivierung erfolgreich abschliessen. Aber auch danach ist Login auf Kundenportal nicht möglich (obwohl ich jetzt regulär nach Token gefragt werde.)

**Sonstiges Problem:**

- OO-DropDown ist kaputt. Bspw. bei Rollenwahl auf Person und auch Projekt defaultSecondFactorType.

2021-04-09 13:03 UTC, AlwinEgger commented on src/main/scala/ch/openolitor/buchhaltung/rechnungsexport/iso20022/Pain008_001_02_Export.scala
> +                "Invalid payment information (group header)"
Ist das von dir oder hast du noch einen Branch von Mikel drinnen?

2021-04-19 04:20 UTC, toggm commented on src/main/scala/ch/openolitor/buchhaltung/rechnungsexport/iso20022/Pain008_001_02_Export.scala
> +                "Invalid payment information (group header)"
Wahrscheunlich habe ich hier eine Warnung betreffend unexhausted match korrigiert

2021-04-19 05:42 UTC, toggm commented
> Merci @toggm für den PR! Hier mein Testresultat (für alle PR auch auf den UI Projekten):
> 
> Ich habe lokal den aktuellen Datenstand eines Projekts als Grundlage genommen; alle 3 PRs der Projekte ausgecheckt):
> 
>     * In Core habe ich kleine Änderungen gemacht (einige Buttons kleiner).
> 
> 
> **Testfälle:**
> 
>     1. Wenn ich als User in meinen Einstellungen den 2nd-Factor-Typ auf OTP wechsle und speichere, werde ich nicht zum initialen Secret-Setzen geführt. Beim ersten Login kommt dies dann. Das ist etwas verwirrlich. Sonst klappts dann gut.
> 
>     2. Als Admin OTP für User zurücksetzen funktioniert. Möglichkeit zur Verbesserung: **Auch für eigenen User(!) und damit brechen wir die im Punkt 4. umgesetzte Sicherheit.**
> 
>     3. OTP wieder verlassen über User-Einstellungen funktioniert auch.
> 
>     4. Second-Factor per E-Mail geht weiterhin. Besoners schön: Für Wechsel zwischen 2nd-Factor Typen muss erst mit 2nd Factor bestätigt werden.
> 
>     5. Als Kunde mit aktiviertem OTP werde ich auf dem Kundenportal nach dem User/Passwort Login zum aufsetzen des OTP aufgefordert. Nach QR-Code-Scan und Eingabe des Codes werde ich zurück auf die Login-Maske geleitet. **Dann Loop. Erfolgreich einloggen nicht möglich.** Wenn ich mit diesem User auf Admin-Portal einlogge, kann ich die OTP-Aktivierung erfolgreich abschliessen. Aber auch danach ist Login auf Kundenportal nicht möglich (obwohl ich jetzt regulär nach Token gefragt werde.)
> 
> 
> **Sonstiges Problem:**
> 
>     * OO-DropDown ist kaputt. Bspw. bei Rollenwahl auf Person und auch Projekt defaultSecondFactorType.

* Login auf Kunenportal via OTP gefixed.
* OO-DropDown kaputt => Kann ich nicht reproduzieren, müssen wir gemeinsam anschauen

2021-04-19 05:45 UTC, toggm commented
> 
>     * Login auf Kunenportal via OTP gefixed.
> 
>     * OO-DropDown kaputt => Kann ich nicht reproduzieren, müssen wir gemeinsam anschauen

Liegt dies evtl. darin, dass noch kein openolitor-client-core release gemacht wurde und demnach nicht die korrekte Version genutzt wird? Oder hast Du lokal ein link gemacht?

2021-04-19 06:44 UTC, AlwinEgger commented
> Liegt dies evtl. darin, dass noch kein openolitor-client-core release gemacht wurde und demnach nicht die korrekte Version genutzt wird? Oder hast Du lokal ein link gemacht?

Ich hatte lokal einen Link gemacht.
Ja, schauen wir uns das Problem dann zusammen an.

2022-03-11 12:41 UTC, mcmpp commented
I have added it to the dev/Seitan branch. We'll merge to Prod from there

2022-03-11 12:41 UTC, closed without merging