Export different types in multiple sheets
OpenOlitor/openolitor-server pull request #598
Opened 2021-10-03 15:03 UTC by AlwinEgger

2021-10-03 18:06 UTC, AlwinEgger commented
Available on Test-Prod

![image](https://user-images.githubusercontent.com/4997364/135766100-209b23e1-d39b-4e6f-9611-89b0d6ea95d6.png)

https://github.com/OpenOlitor/operations/issues/452

2021-10-04 04:51 UTC, toggm requested changes

2021-10-04 04:51 UTC, toggm commented on src/main/scala/ch/openolitor/core/RouteService.scala
> +                    clazzSortedList.head match {
Ein `nonEmpty` check wäre hier wohl noch sinnvoll

2021-10-04 06:50 UTC, AlwinEgger commented on src/main/scala/ch/openolitor/core/RouteService.scala
> +                    clazzSortedList.head match {
Auf der ganzen Liste wird ja auf Zeile 353 ein nonEmpty-Check gemacht. Eine Liste resultierend aus dem groupBy nach Klasse kann dann doch nicht empty sein...

2021-10-04 06:55 UTC, toggm commented on src/main/scala/ch/openolitor/core/RouteService.scala
> +                    clazzSortedList.head match {
Stimmt wohl ;-)

2021-10-04 06:55 UTC, toggm approved these changes

2021-10-04 07:05 UTC, merged