OTP integration:fix merge issue on Document Processor
OpenOlitor/openolitor-server pull request #614
Opened 2022-03-14 11:09 UTC by mcmpp

2022-03-14 11:18 UTC, toggm requested changes
There are other locations where `parseFormat` is still used wrongly. You need to replace all of them.

2022-03-14 12:00 UTC, mcmpp commented
Sorry, I didn't see it. I have submitted now all functions and modifications on the main function

2022-03-15 05:30 UTC, toggm commented on src/main/scala/ch/openolitor/core/reporting/DocumentProcessor.scala
> +        case name :: Nil  => (correctPropertyName(propertyName.trim), Nil)
actual prod has:
```
propertyName.split('|').toList match {
        case name :: Nil  => (correctPropertyName(name.trim), Nil)
        case name :: tail => (correctPropertyName(name.trim), tail.map(_.trim))
        case _            => (correctPropertyName(propertyName), Nil)
      }
```

2022-03-16 11:15 UTC, mcmpp commented on src/main/scala/ch/openolitor/core/reporting/DocumentProcessor.scala
> +        case name :: Nil  => (correctPropertyName(propertyName.trim), Nil)
done

2022-03-16 15:29 UTC, toggm approved these changes

2022-03-16 15:36 UTC, merged